import '../models/video_model.dart';

// Données fictives pour simuler les vidéos TikTok
final List<VideoModel> dummyVideos = [
  VideoModel(
    id: '1',
    username: '@user1',
    caption: 'Découvrez ce nouveau challenge #trending #viral',
    songName: 'Son original - Artiste Populaire',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-waving-outdoors-1226-large.mp4',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/85.jpg',
    likes: 12500,
    comments: 350,
    shares: 120,
  ),
  VideoModel(
    id: '2',
    username: '@danceking',
    caption: 'Nouvelle chorégraphie 🔥 #dance #viral',
    songName: 'Hit du moment - Top Artist',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-portrait-of-a-fashion-woman-with-silver-makeup-39875-large.mp4',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    likes: 45800,
    comments: 1200,
    shares: 580,
  ),
  VideoModel(
    id: '3',
    username: '@comedyqueen',
    caption: 'Quand tu essaies de faire un TikTok sérieux 😂 #comedy #fail',
    songName: 'Musique drôle - Comédien',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-sign-1232-large.mp4',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/43.jpg',
    likes: 98700,
    comments: 3400,
    shares: 1250,
  ),
  VideoModel(
    id: '4',
    username: '@travelbug',
    caption: 'Explorant ce lieu magnifique ✈️ #travel #adventure',
    songName: 'Musique de voyage - Explorateur',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-tree-with-yellow-flowers-1173-large.mp4',
    profileImageUrl: 'https://randomuser.me/api/portraits/women/21.jpg',
    likes: 35600,
    comments: 450,
    shares: 280,
  ),
  VideoModel(
    id: '5',
    username: '@foodlover',
    caption: 'Recette facile et délicieuse 🍕 #food #recipe',
    songName: 'Musique gourmande - Chef',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-serving-dinner-to-a-guest-4633-large.mp4',
    profileImageUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
    likes: 28900,
    comments: 670,
    shares: 340,
  ),
];
